#!/bin/sh
ScriptDir=`dirname $0`
source ${ScriptDir}/components/vars.sh

if test -z "$1"; then
	echo "Usage: $0 <ProjectName>"
	exit 0
fi

ProjectName=$1
UpperProjectName=`echo "${ProjectName}" | tr '[:lower:]' '[:upper:]'`


ChangeProjectName() {
	echo "Renaming project in $1/$2"
	sed -i -e "s/ProjectName/${ProjectName}/g" \
	       -e "s/PROJECTNAME/${UpperProjectName}/g" \
	       $1/$2
}
ChangeFileName() {
	echo "Renaming filename: \"$1/$2\" -> \"$1/$3\""
	mv "$1/$2" "$1/$3"
}

if test -d "${ProjectName}"; then
	echo "The project \"${ProjectName}\" is already exists. "
	exit 1;
fi

echo "Copy template..."
cp -r ${TemplateDir}/project ${ProjectName}

cd ${ProjectName}
ls --color

ChangeProjectName .     README.md
ChangeProjectName .     CMakeLists.txt
ChangeProjectName ext   CMakeLists.txt
ChangeProjectName src   CMakeLists.txt
ChangeProjectName test  CMakeLists.txt

ChangeProjectName src   main.c
ChangeProjectName src   ProjectName.c
ChangeProjectName test  ProjectNameTest.cpp

ChangeFileName    src   ProjectName.c ${ProjectName}.c
ChangeFileName    test  ProjectNameTest.cpp ${ProjectName}Test.cpp

echo "Done."
cd ${OriginDir}
